apt-get update;
apt-get install sudo;
apt-get install bsdutils;
apt-get install curl;
apt-get install -y build-essential;
apt-get install -y python-software-properties;
apt-get install -y php5;
apt-get install -y apache2;
apt-get install -y libapache2-mod-php5;
apt-get install -y mysql-server;
